[pidf]
kP = 1.0
kI = 0.0
kD = 0.0
kF = 0.0
kIZ = 0.0

[localizations]
width = 29.0
length = 32.0
wheelDiameter = 6.0
maxVelocity = 0.0
maxAcceleration = 0.0
maxJerk = 0.0

[ports]
front_left = 1
back_left = 2
front_right = 3
back_right = 4
