slowdownCloseThreshold = 3.8
slowdownExtendThreshold = 10.0
slowdownOpenThreshold = 24.5
slowdownResetThreshold = 9.0
slowdownPickupThreshold = 20.0

stopOverdriveThreshold = 25.5

rumbleAngularPowerRequirement = 0.2

[lowGearSlowing]
startRampArea = 0.5
endRampArea = 5.0
minimumSpeed = 0.25

[highGearSlowing]
startRampArea = 0.27
endRampArea = 3.0
minimumSpeed = 0.0
