minSpeed = 0.25
startRampArea = 0.5
endRampArea = 6.0

slowdownCloseThreshold = 3.8
slowdownExtendThreshold = 13.0
slowdownOpenThreshold = 23.0
slowdownResetThreshold = 13.0
slowdownPickupThreshold = 20.0

stopOverdriveThreshold = 24.0
